import { Metadata } from "next";
import Providers from "../components/Providers";
import '../styles/globals.css'
import Header from "@/components/Header";
import Footer from "@/components/Footer";

export const metadata : Metadata = {
  title: 'The Actual News',
  description: 'Generated by create next app',
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body>
        <Providers>
          <div className="min-h-screen dark:bg-slate-900 bg-gray-50">
            <Header />
            <div className="container mx-auto mt-3">{children}</div>
          </div>
          <Footer />
        </Providers>
        </body>
    </html>
  )
}
